INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Shaiden Rogue',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Gina Valentina',NULL,'Latin',NULL,'Rio de Janeiro, Brazil',0,'Black','5 ft 2 in (157 cm)',1,1,NULL),
	 ('Reagan Foxx',NULL,'White',NULL,'Arizona, United States of America',0,'Brunette','5 ft 9 in (175 cm)',1,0,NULL),
	 ('Kuleana',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Cherie Deville',NULL,'White','American','Durham, North Carolina, United States of America',0,'Brunette','5 ft 5 in (165 cm)',1,1,NULL),
	 ('LaSirena69',NULL,'Latin',NULL,'Venezuela',1,'Brunette','5 ft 1 in (155 cm)',1,0,NULL),
	 ('Alex Coal','676098000000','White','American','Las Vegas, Nevada, United States of America',0,'Black','5 ft 3 in (160 cm)',0,0,''),
	 ('Eliza Ibarra',NULL,'Latin',NULL,'Riverside, California, United States of America',0,'Brunette','5 ft 10 in (178 cm)',0,0,NULL),
	 ('Gianna Dior',NULL,'White',NULL,'Auburn, Alabama, United States of America',1,'Brunette','5 ft 5 in (165 cm)',0,0,NULL),
	 ('Jada Stevens',NULL,'White',NULL,'Snellville, Georgia, United States of America',1,'Blonde','5 ft 3 in (160 cm)',0,1,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Abigail Mac',NULL,'Other','American','United States of America',1,'Brunette','5 ft 2 in (157 cm)',1,0,NULL),
	 ('Alina Lopez',NULL,'Latin',NULL,'Los Angeles, California, United States of America',1,'Brunette','5 ft 6 in (168 cm)',0,1,NULL),
	 ('Gabbie Carter',NULL,'White','American','Austin, Texas, United States of America',1,'Blonde','5 ft 7 in (170 cm)',0,1,NULL),
	 ('Kelsi Monroe',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Mandy Muse',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Aubrey Sinclair',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Lana Rhoades',NULL,'White',NULL,'Chicago, Illinois, United States of America',0,'Brunette','5 ft 5 in (165 cm)',0,0,NULL),
	 ('Jessika Lux',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Havana Bleu',NULL,'Latin',NULL,'Cuba',1,'Brunette','5 ft 3 in (160 cm)',1,0,NULL),
	 ('Leah Gotti',NULL,'Other','American','Dallas, Texas, United States of America',1,'Brunette','5 ft 4 in (163 cm)',0,1,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Ashley Wolf',NULL,'White','German','United States of America',1,'Brunette','5 ft 6 in (168 cm)',0,1,NULL),
	 ('Emma Jade',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Avi Love',NULL,NULL,NULL,'Nevada, United States of America',0,'Brunette','5 ft 6 in (168 cm)',0,0,NULL),
	 ('Emily Willis',NULL,'White',NULL,'St George, Utah, United States of America',0,'Brunette','5 ft 5 in (165 cm)',0,0,NULL),
	 ('Kat Dior',NULL,'Asian',NULL,'United States of America',1,'Brunette','5 ft 2 in (157 cm)',1,1,NULL),
	 ('Ava Addams',NULL,'White','French','Gibraltar, France',0,'Brunette','5 ft 3 in (160 cm)',1,1,NULL),
	 ('Rikki Six',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Ginebra Bellucci',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Baby Nicols',NULL,'Latin','Venezuelan','Laguaira, Venezuela',0,'Brunette','5 ft 3 in (160 cm)',0,0,NULL),
	 ('Aria Lee',NULL,'Asian',NULL,'Los Angeles, California, United States of America',0,'Brunette','5 ft 2 in (157 cm)',0,0,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Lexi Luna',NULL,'White',NULL,'Florida, United States of America',0,'Brunette','5 ft 7 in (170 cm)',1,0,NULL),
	 ('Luna Star',NULL,'Latin',NULL,'Cuba',1,'Blonde|Brunette|Black','5 ft 4 in (163 cm)',1,1,NULL),
	 ('Karma Rx',NULL,'White',NULL,'United States of America',1,'Blonde','5 ft 4 in (163 cm)',1,1,NULL),
	 ('Ashly Anderson',NULL,'White',NULL,'Enterprise, Alabama, United States of America',0,'Brunette','5 ft 4 in (163 cm)',1,0,NULL),
	 ('Clea Gaultier',NULL,'White','Lebanese','France',1,'Brunette','5 ft 5 in (165 cm)',0,1,NULL),
	 ('Blake Blossom',NULL,'White','German',NULL,0,'Blonde','5 ft 7 in (170 cm)',0,0,NULL),
	 ('Veronica Rodriguez',NULL,'Latin',NULL,'Venezuela',1,'Brunette','5 ft 3 in (160 cm)',0,1,NULL),
	 ('Rachael Cavalli',NULL,'White',NULL,'Indianapolis, Indiana, United States of America',1,'Blonde','5 ft 9 in (175 cm)',0,1,NULL),
	 ('Vanna Bardot',NULL,'White','Brazilian','Miami, Florida, United States of America',1,'Auburn','5 ft 4 in (163 cm)',0,1,NULL),
	 ('Abella Danger',NULL,'White',NULL,'Miami, Florida, United States of America',0,'Brunette','5 ft 4 in (163 cm)',0,0,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Vanessa Sky',NULL,'Latin',NULL,'Rapid City, South Dakota, United States of America',1,'Black','5 ft 3 in (160 cm)',0,1,NULL),
	 ('Lulu Chu',NULL,'Asian','American','United States of America',1,'Blonde','5 ft 0 in (152 cm)',0,1,NULL),
	 ('Eva Lovia',NULL,'White','Japanese','Los Angeles, California, United States of America',1,'Brunette','5 ft 3 in (160 cm)',0,1,NULL),
	 ('Tia Cyrus',NULL,'Latin',NULL,'Hayward, California, United States of America',1,'Black','5 ft 0 in (152 cm)',1,1,NULL),
	 ('Jessica Lux',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Maddy Oreilly',NULL,'White',NULL,'North Carolina, United States of America',1,'Brunette','5 ft 7 in (170 cm)',0,1,NULL),
	 ('Nicole Aniston',NULL,'White',NULL,'San Diego, California, United States of America',1,'Blonde','5 ft 3 in (160 cm)',1,1,NULL),
	 ('Eva Long',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Uma Jolie',NULL,'White',NULL,'California, United States of America',0,'Brunette','5 ft 3 in (160 cm)',0,0,NULL),
	 ('Kyler Quinn',NULL,'White',NULL,'Arizona, United States of America',0,'Brunette','5 ft 5 in (165 cm)',0,1,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Lexi Aaane',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Ariana Fuentes',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Kayla Kayden',NULL,'White',NULL,'Syracuse, New York, United States of America',1,'Blonde','5 ft 2 in (157 cm)',1,1,NULL),
	 ('Aidra Fox',NULL,'White','American','Wisconsin, United States of America',0,'Red','5 ft 7 in (170 cm)',0,1,NULL),
	 ('Jewelz Blu',NULL,'White','German','Germany',0,'Other','5 ft 6 in (168 cm)',1,0,NULL),
	 ('Arya Fae',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Megan Sage',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Marica',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Nikki',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Sammie Rhodes',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Kendra Banx',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Aria Alexander',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Medi Meadows',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Keisha Grey',NULL,'White',NULL,'Tampa, Florida, United States of America',1,'Brunette','5 ft 3 in (160 cm)',0,1,NULL),
	 ('Celeste Star',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Jill Kassidy',NULL,'White',NULL,'Dallas, Texas, United States of America',1,'Brunette','5 ft 6 in (168 cm)',0,0,NULL),
	 ('Valerica Steele',NULL,'White',NULL,NULL,1,'Other','5 ft 2 in (157 cm)',1,1,NULL),
	 ('Martina Smeraldi',NULL,'White','Italian',NULL,1,'Brunette','5 ft 4 in (163 cm)',0,1,NULL),
	 ('Gisele Montes',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Anastasia Knight',NULL,'White',NULL,'Pompano Beach, Florida, United States of America',0,'Blonde','5 ft 3 in (160 cm)',0,0,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Liya Silver',NULL,'White',NULL,'Russia',0,'Brunette','5 ft 4 in (163 cm)',0,1,NULL),
	 ('Mi Ha Doan',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Maya Woulfe',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Charlie Valentine',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Brooklyn Chase',NULL,'White',NULL,'San Diego, California, United States of America',0,'Brunette','5 ft 2 in (157 cm)',1,1,NULL),
	 ('Kylie Quinn',NULL,'White',NULL,'Florida, United States of America',0,'Brunette','5 ft 5 in (165 cm)',0,0,NULL),
	 ('Ariana Marie',NULL,'White','Puerto Rican','Dallas, Texas, United States of America',1,'Brunette','5 ft 5 in (165 cm)',0,1,NULL),
	 ('Desiree Dulce',NULL,'Latin','Puerto Rican','United States of America',1,'Brunette','5 ft 8 in (173 cm)',1,0,NULL),
	 ('Aubree Valentine',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Lyra Law',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Violet Starr',NULL,'White',NULL,'Tampa, Florida, United States of America',0,'Brunette','5 ft 5 in (165 cm)',0,0,NULL),
	 ('Ava Dalush',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Naomi Swann',NULL,'White',NULL,'Fort Pierce, Florida, United States of America',0,'Brunette','5 ft 3 in (160 cm)',0,1,NULL),
	 ('Valentina Nappi',NULL,'Other','Italian','Pompei, Italy',1,'Brunette','5 ft 5 in (165 cm)',0,0,NULL),
	 ('Kylie Rocket',NULL,'Latin','Puerto Rican',NULL,1,'Brunette',NULL,0,1,NULL),
	 ('Lily Larimar',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Alex Grey',NULL,'White',NULL,'Fort Benning, Georgia, United States of America',0,'Blonde','5 ft 2 in (157 cm)',0,1,NULL),
	 ('Lilly Bell',NULL,'White',NULL,'California, United States of America',1,'Blonde','5 ft 1 in (155 cm)',0,1,NULL),
	 ('MacKenzie Mace',NULL,'White',NULL,'Miami, Florida, United States of America',1,'Other','5 ft 3 in (160 cm)',0,0,NULL),
	 ('Casca Akashova',NULL,'White',NULL,'Russia',0,'Blonde','5 ft 3 in (160 cm)',1,1,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Alice Pink',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Anikka Albrite',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Madelyn Monroe',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Eva Notty',NULL,'White',NULL,'Phoenix, Arizona, United States of America',0,'Blonde','5 ft 9 in (175 cm)',1,1,NULL),
	 ('XxLayna Marie',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Blondie Fesser',NULL,'White','German','Buenos Aires, Argentina',1,'Blonde','5 ft 3 in (160 cm)',1,1,NULL),
	 ('Sofia Lee',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Mandy Flores',NULL,'White','American','Seattle, Washington, United States of America',0,'Brunette','5 ft 4 in (163 cm)',1,0,NULL),
	 ('Jessie Saint',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Tru Kait',NULL,'Latin','Mexican',NULL,1,'Brunette','5 ft 2 in (157 cm)',0,0,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Rebeca Linares',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Joseline Kelly',NULL,'White',NULL,'Atlanta, Georgia, United States of America',1,'Brunette','5 ft 4 in (163 cm)',0,1,NULL),
	 ('Kristen Scott',NULL,'White',NULL,'San Diego, California, United States of America',1,'Blonde','5 ft 2 in (157 cm)',0,1,NULL),
	 ('Jessica Jaymes',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Tasha Reign',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('The Needy Babysitter',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Mischa Brooks',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Sheena Shaw',NULL,'White','French','United States of America',1,'Auburn','5 ft 0 in (152 cm)',0,1,NULL),
	 ('Dana Wolf',NULL,'White',NULL,'Miami, Florida, United States of America',1,'Brunette','5 ft 9 in (175 cm)',0,0,NULL),
	 ('Angeline Red',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Val Steele',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Autumn Falls',NULL,'Latin','Puerto Rican','New York City, New York, United States of America',1,'Brunette','5 ft 3 in (160 cm)',0,0,NULL),
	 ('Maddy May',NULL,'White','American',NULL,0,'Brunette','5 ft 2 in (157 cm)',1,1,NULL),
	 ('Gia Paige',NULL,'White',NULL,'Detroit, Michigan, United States of America',1,'Brunette','5 ft 2 in (157 cm)',0,1,NULL),
	 ('Kendra Sunderland',NULL,'White',NULL,'Salem, Oregon, United States of America',0,'Blonde','5 ft 9 in (175 cm)',0,1,NULL),
	 ('Josephine Jackson',NULL,'White',NULL,NULL,1,'Brunette','5 ft 2 in (157 cm)',0,0,NULL),
	 ('Crystal Rush',NULL,'White',NULL,'Russia',1,'Brunette','5 ft 3 in (160 cm)',1,0,NULL),
	 ('Rose Winters',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Penny Barber',NULL,'White',NULL,'San Francisco, California, United States of America',0,'Brunette','5 ft 6 in (168 cm)',1,0,NULL),
	 ('Alyssia Kent',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Avery Cristy',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Gaby Ortega',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Armani Dream',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Jaimie Vine',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Eden Ivy',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Alyson Thor',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Lillith Morningstar',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Angie Lynx',NULL,'White','Finnish',NULL,1,'Blonde','5 ft 4 in (163 cm)',1,1,NULL),
	 ('Jessica Ryan',NULL,'White','British','Colorado, United States of America',1,'Red','5 ft 3 in (160 cm)',0,1,NULL),
	 ('Veronica Leal',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Mells Blanco',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Pristine Edge',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Aaliyah Hadid',NULL,'Latin',NULL,'Sanford, North Carolina, United States of America',0,'Black','5 ft 6 in (168 cm)',1,0,NULL),
	 ('Jasmine Wilde',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Tommy King',NULL,'White','Dutch',NULL,0,'Brunette','5 ft 5 in (165 cm)',0,1,NULL),
	 ('Bailey Base',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Cory Chase',NULL,'White','American','New Jersey, United States of America',1,'Blonde','5 ft 5 in (165 cm)',1,0,NULL),
	 ('Isabella De Santos',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Sara Blonde',NULL,'White','Colombian',NULL,1,'Blonde','5 ft 3 in (160 cm)',0,1,NULL),
	 ('Patricia Acevedo',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Letzy Lizz',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Silvana Lee',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Michel Chica',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Sarah Taylor',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Natalia GarcÃ­a',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Jessica Sodi',NULL,'Latin','Latin',NULL,0,'Red','5 ft 4 in (163 cm)',0,1,NULL),
	 ('Nicole Zurich',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Haley Reed',NULL,'White',NULL,'Florida, United States of America',1,'Blonde','5 ft 10 in (178 cm)',0,1,NULL),
	 ('Auror',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Lexi Lore',NULL,'White',NULL,'Richmond, Virginia, United States of America',1,'Blonde','5 ft 5 in (165 cm)',0,1,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Carolina Sweets',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Riley Steele',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Stevie Shae',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Sharon White',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Mia Kay',NULL,'White','American',NULL,0,'Brunette','5 ft 2 in (157 cm)',0,1,NULL),
	 ('Molly Little',NULL,'White',NULL,NULL,0,'Blonde','5 ft 3 in (160 cm)',0,0,NULL),
	 ('Whitney Wright',NULL,'White',NULL,'Oklahoma City, Oklahoma, United States of America',0,'Brunette','5 ft 6 in (168 cm)',0,0,NULL),
	 ('Natalie Brooks',NULL,'Latin','Honduran','Miami, United States of America',0,'Brunette','5 ft 2 in (157 cm)',0,1,NULL),
	 ('Crystal Clark',NULL,'White','Irish','United States of America',0,'Blonde','5 ft 4 in (163 cm)',1,0,NULL),
	 ('Cassie Del Isla',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL);
INSERT INTO Actor (ActorName,BirthDate,Ethinicity,Nationality,BirthPlace,Drilling,HairColor,Height,NaturalBoobs,Tattoos,Image) VALUES
	 ('Lacey Channing',NULL,NULL,NULL,NULL,0,NULL,NULL,0,0,NULL),
	 ('Sofie Reyez',NULL,'Latin',NULL,'West Palm Beach, Florida, United States of America',1,'Brunette','5 ft 1 in (155 cm)',0,1,NULL);
